name: Deploy App
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build

      - name: Edgeserver v0.2 Upload
        uses: v3xlabs/edgeserver-upload@v0.2.1-pre.4
        with:
          site_id: s_1194314723
          server: https://edgeserver.dev/api
          token: ${{ secrets.EDGE_TOKEN }}
          directory: dist
          context: true
